camera/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    # url(r'^$', IndexView.as_view(), name='index'),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^situation/', SituationView.as_view(), name='situation'),
    url(r'^different/', DifferentView.as_view(), name='different'),
    url(r'^prevent/', PreventView.as_view(), name='prevent'),
]

introduce/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    # url(r'^$', IndexView.as_view(), name='index'),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^story/', StoryView.as_view(), name='story'),
    url(r'^effect/', EffectView.as_view(), name='effect'),
    url(r'^future/', FutureView.as_view(), name='future'),
]

jejudaum/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from .views import *

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^list$', RoomList.as_view(), name='room_list'),
    url(r'^detail/(?P<pk>\d+)$', RoomDetail.as_view(), name='room_detail'),
    url(r'^new$', login_required(RoomCreate.as_view()), name='room_new'),
    url(r'^edit/(?P<pk>\d+)$', login_required(RoomUpdate.as_view()), name='room_edit'),
    url(r'^delete/(?P<pk>\d+)$', login_required(RoomDelete.as_view()), name='room_delete'),
    url(r'^change/$',login_required(RoomChangeList.as_view()), name="room_change"),
]

openSource/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from openSource.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^camera/', include('camera.urls', namespace='camera')),
    # url(r'^crimer/', include('crimer.urls', namespace='crimer')),
    # url(r'^community/', include('community.urls', namespace='community')),
    url(r'^introduce/', include('introduce.urls', namespace='introduce')),
    url(r'^com/', include('jejudaum.urls', namespace='jejudaum')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),


    url(r'^$', HomeView.as_view(), name='home'),
]

camera/models.py
from django.db import models

# Create your models here.

introduce/models.py
from django.db import models

# Create your models here.

jejudaum/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class Room_info(models.Model):
    owner = models.ForeignKey(User, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    create_date = models.DateTimeField( #날째
            blank=True, null=True, auto_now_add = True);

    class Meta:
        ordering = ['-create_date']

    def __str__(self):
        return self.title

openSource/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django import forms

class CreateUserForm(UserCreationForm): # 내장 회원가입 폼을 상속받아서 확장한다.
    email = forms.EmailField(required=True) # 이메일 필드 추가
    phone_number = forms.RegexField(regex=r'^\+?1?\d{9,15}$',
                                error_message = ("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."))
    class Meta:
        model = User
        fields = ("username", "email", "phone_number", "password1", "password2")

    def save(self, commit=True): # 저장하는 부분 오버라이딩
        user = super(UserCreationForm, self).save(commit=False) # 본인의 부모를 호출해서 저장하겠다.
        user.email = self.cleaned_data["email"]
        user.phone_number = self.cleaned_data["phone_number"]

        if commit:
            user.save()

        return user

camera/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import TemplateView

class IndexView(TemplateView):
    template_name = 'camera/index.html'

class SituationView(TemplateView):
    template_name = 'camera/situation.html'

class DifferentView(TemplateView):
    template_name = 'camera/different.html'

class PreventView(TemplateView):
    template_name = 'camera/prevent.html'

introduce/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import TemplateView

class IndexView(TemplateView):
    template_name = 'introduce/index.html'

class StoryView(TemplateView):
    template_name = 'introduce/story.html'

class EffectView(TemplateView):
    template_name = 'introduce/effect.html'

class FutureView(TemplateView):
    template_name = 'introduce/future.html'

jejudaum/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from .models import Room_info

class IndexView(TemplateView):
    template_name = 'jejudaum/index.html'

class RoomList(ListView):
    model = Room_info
    paginate_by = 10
    template_name = 'jejudaum/room_list.html'

class RoomDetail(DetailView):
    model = Room_info
    template_name = 'jejudaum/room_detail.html'

class RoomCreate(CreateView):
    template_name = 'jejudaum/room_new.html'
    model = Room_info
    fields = ['title', 'content']
    success_url = reverse_lazy('jejudaum:room_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(RoomCreate, self).form_valid(form)

class RoomChangeList(ListView):
    template_name = 'jejudaum/room_change_list.html'

    def get_queryset(self):
        return Room_info.objects.filter(owner = self.request.user)

class RoomUpdate(UpdateView):
    template_name = 'jejudaum/room_new.html'
    model = Room_info
    fields = ['title', 'content']
    success_url = reverse_lazy('jejudaum:room_list')

class RoomDelete(DeleteView):
    model = Room_info
    template_name = 'jejudaum/room_delete.html'
    success_url = reverse_lazy('jejudaum:room_list')

openSource/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.decorators import login_required
# from .forms import CreateUserForm


class HomeView(TemplateView):
    template_name = 'index.html'

#--- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

camera/templates/camera/different.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'camera:index'%}{%endblock%}
{%block srctwo%}{% url 'camera:situation'%}{%endblock%}
{%block srcthree%}{% url 'camera:different'%}{%endblock%}
{%block srcfour%}{% url 'camera:prevent'%}{%endblock%}

{%block onetitle%}몰래카메라란?{%endblock%}
{%block twotitle%}몰래카메라 피해 상황{%endblock%}
{%block threetitle%}몰래카메라 종류{%endblock%}
{%block fourtitle%}몰래카메라 예방법{%endblock%}

<style>
.flex-container {
    display: -webkit-flex;
    display: flex;
    width: 75%;
    /*height: 250px;*/
    background-color: lightgrey;
}

img.col-md-3 {
    background-color: cornflowerblue;
    width: 100px;
    height: 100px;
    margin: 10px;
}

img.col-md-3:hover{
  background-color: : rgba(196, 94, 94, 0.5);
}
</style>


{%block content%}
<h3>몰래카메라는 애초에 목적이 사람들에게 발각되지 않고 촬영하기 위한 것이기 때문에 사실상 몰래카메라를 완벽하게 구별하거나 찾아내기는 어렵습니다. 몰래카메라 탐지기가 있기는 하지만 일반인들이 탐지기를 가지고 다니며 사용하는 것은 현실성이 없기 때문에 몰래카메라에 한없이 무방비할 수밖에 없습니다.
화장실 같은 곳에서는 항상 주변을 경계하고 이상한 점이 있는지 체크하는 습관을 가져야 합니다.
</h3>

<div class="flex-container">


<img class="col-md-3" src="{% static 'img/camera/몰래카메라 넥타이형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 단추형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 라이터형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 마우스형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 모자형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 보온병형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 볼펜형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 스위치형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 안경형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 액자형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 차키형.JPG'%}" alt="">
<img class="col-md-3" src="{% static 'img/camera/몰래카메라 usb형.JPG'%}" alt="">
</div>

{%endblock content%}

camera/templates/camera/index.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'camera:index'%}{%endblock%}
{%block srctwo%}{% url 'camera:situation'%}{%endblock%}
{%block srcthree%}{% url 'camera:different'%}{%endblock%}
{%block srcfour%}{% url 'camera:prevent'%}{%endblock%}

{%block onetitle%}몰래카메라란?{%endblock%}
{%block twotitle%}몰래카메라 피해 상황{%endblock%}
{%block threetitle%}몰래카메라 종류{%endblock%}
{%block fourtitle%}몰래카메라 예방법{%endblock%}


{%block content%}

<h1 style="color: rgb(104, 164, 196);">몰래카메라란?</h1>
<br>

<h2>-촬영을 당하는 사람이 촬영을 당한다는 사실을 모르는 상태로 <br> &nbsp;촬영하는 카메라. 또는 그런 방식.</h2>

​

<h4></h4>
<h4 style=" color: #656565;">최근 스마트폰 보급이 확산되고 초소형 카메라 등 첨단 기술 장비가 발전하면서 몰래카메라 범죄가 기승을 부리고 있습니다.</h4>
<h4 style=" color: #656565;">주로 몰래 카메라 범죄에 이용된 도구로는 휴대전화가 82%로 높은 비율을 차지했으며,
 휴대전화가 있는 주변 어디에서나 몰래카메라에 의한 범죄가 일어날 지도 모른다는 불안감을 조성합니다.</h4>
<h4 style=" color: #656565;">개인의 호기심에서 시작된 몰래 카메라 범죄는 이제 몰래카메라로 찍은 영상이 불법적으로 유통되는 모습으로까지 등장하고 있고 점점 조직적인 범죄로 확대되어가고 있습니다.</h4>
<h4 style=" color: #656565;">몰래 카메라 검색으로 수많은 음란 동영상이 유출되고 있지만, 범인들은 피해자에게 직접가해를 입히지 않는다고 생각해서 죄책감을 느끼지 않고 반복적인 범죄를 저지르게 된다고 합니다.
몰래카메라의 눈에 띄지 않는 성격 때문에 여성들은  무방비하게 몰래카메라의 위험에 노출되고 있습니다. </h4>​
​

<h4 style=" color: #656565;">-몰래카메라에 관한 법령</h4>

<h4 style=" color: #656565;">1. 몰래카메라의 경우 성폭력범죄의 처벌 등에 관한 특례법 제14조 제1항(카메라 등을 이용한 촬영) 위반으로 5년 이하 징역 또는 1천만원 이하 벌금형에 처해진다.</h4>​
<h4 style=" color: #656565;">2. 성매매 알선 행위에 대해서는 관련 법률 제19조 제2항(벌칙)에 따라 7년 이하 징역 또는 7천만원 이하 벌금형을 받는다.</h4>
<h4 style=" color: #656565;">3. 영리를 목적으로 그 촬영물을 인터넷 등 정보통신망을 이용하여 유포하면 7년 이하의 징역 또는 3천만원 이하의 벌금형에 처해진다.</h4>



​​
​
​

​
​

{%endblock content%}

camera/templates/camera/prevent.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'camera:index'%}{%endblock%}
{%block srctwo%}{% url 'camera:situation'%}{%endblock%}
{%block srcthree%}{% url 'camera:different'%}{%endblock%}
{%block srcfour%}{% url 'camera:prevent'%}{%endblock%}

{%block onetitle%}몰래카메라란?{%endblock%}
{%block twotitle%}몰래카메라 피해 상황{%endblock%}
{%block threetitle%}몰래카메라 종류{%endblock%}
{%block fourtitle%}몰래카메라 예방법{%endblock%}

{%block content%}
<style media="screen">
  li{
    font-size: 22px;
  }
</style>
<h3>화장실에서:</h3>
<ol>
  <li>부자연스러운 위치의 나사는 무조건 의심합니다.</li>
  <li>화장실에 있는 휴지통에 신문지를 깔고 그 안에 카메라를 숨기는 경우가 많으므로 신문지가 가장 위에 있을 경우 휴지를 뜯어 신문지를 덮거나 휴지통을 반대로 돌립니다.</li>
  <li>화장실 옆 칸의 밑 부분의 공간이 많다면 조심합니다. 그 공간으로 촬영을 감행하기 때문입니다.</li>
  <li>사람의 인기척이 있다면 볼일 보는 중이라도 천정을 살펴봅니다. 되도록 양 끝칸을 이용합니다.</li>
</ol>

<br>
<h3>숙박업소에서:</h3>
<ol>
  <li>실내 조명을 전부 소등하고 휴대전화 플래시를 비췄을 때 ‘반짝’하고 빛이 나는 곳이 있는지 살핍니다.</li>
  <li>직원이 권유하는 방 말고 다른 방을 택하는게 좋습니다.</li>
</ol>

<br>
<h3>그 외 몰래카메라 피해가 많은 공간에서 :</h3>
<ol>
  <li>계단을 오르내릴 때 가방이나 책으로 가려줍니다. 에스컬레이터는 45도 각도로 몸을 비틀어 탑니다.</li>
  <li> 사람이 많은 곳에서는 오래 서있지 말고 5~10분 단위로 자리를 옮기는 것이 좋습니다.</li>
  <li> 여름철 해수욕장이나 수영장에서 항상 주위를 살피고 촬영음은 없는지, 모르는 사람이 계속 따라온다던지, 이상한 느낌이 든다면 바로 그 자리를 떠야합니다.</li>
  <li> 나를 향해 주변에 가방이나 수건에 쌓여진 물품이 없는지 확인합니다.</li>
  <li> 몰래카메라의 흔적을 발견하거나, 사람을 발견하게 된다면 바로 신고합니다.</li>

</ol>


{%endblock content%}

camera/templates/camera/situation.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'camera:index'%}{%endblock%}
{%block srctwo%}{% url 'camera:situation'%}{%endblock%}
{%block srcthree%}{% url 'camera:different'%}{%endblock%}
{%block srcfour%}{% url 'camera:prevent'%}{%endblock%}

{%block onetitle%}몰래카메라란?{%endblock%}
{%block twotitle%}몰래카메라 피해 상황{%endblock%}
{%block threetitle%}몰래카메라 종류{%endblock%}
{%block fourtitle%}몰래카메라 예방법{%endblock%}


{%block content%}
<style>
#logo{
  height:auto;
  width: 800px

}
</style>

<h1 style="color: rgb(104, 164, 196);">몰래카메라 피해 상황</h1>
<br>

<iframe width="850" height="400" src="https://www.youtube.com/embed/n3ygtAE8Hi4" frameborder="0" allowfullscreen></iframe>
<br>
<h4  style=" color: #656565;"> 이제 안전한 곳은 없습니다. 여성들은 가장 사적인 공간인 화장실마저도 몰래카메라 때문에 안심하고 사용하지 못합니다.
공중 여성화장실 몰래카메라 피해가 속출하고 있지만, 갈수록 교묘해지는 몰카 장비에, 공중화장실을 관리하는 사람도 모르고, 이용하는 사람은 더욱 알 수 없는 불안한 상황이 계속되고 있습니다.</h4>
<h4><몰래 카메라 때문에 스카프 쓰고다니는 사연></h4>
<h4><img id="logo" alt="" src="{% static 'img/event1.jpg'%}" /></h4>
<h4><몰카, 신체접촉,, 제주 해수욕장에서 성범죄 주의보></h4>
<h4><img id="logo" alt="" src="{% static 'img/event2.png'%}" /></h4>
<h4>제주 공중화장실에 몰카설치,, 100명 사진 유포한 30대</h4>
<h4><img id="logo" alt="" src="{% static 'img/event3.jpg'%}" /></h4>


{%endblock content%}

introduce/templates/introduce/effect.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'introduce:index'%}{%endblock%}
{%block srctwo%}{% url 'introduce:story'%}{%endblock%}
{%block srcthree%}{% url 'introduce:effect'%}{%endblock%}
{%block srcfour%}{% url 'introduce:future'%}{%endblock%}

{%block onetitle%}안심벨이란?{%endblock%}
{%block twotitle%}안심벨의 이야기{%endblock%}
{%block threetitle%}안심벨로 인해 생긴일{%endblock%}
{%block fourtitle%}안심벨의 미래{%endblock%}
{%block content%}
<style>
h4{
  line-height: 30px;
}
</style>
<h1 style="color: rgb(104, 164, 196);">&nbsp;안심벨로 인해 생긴일</h1>
<h4 style=" color: #656565;"> &nbsp;안심벨이 생긴 이후 많은 여성들이 많은 위협으로부터 안전하게 생활할 수 있어졌습니다.
정확하게 그 효과를 보여주는 사건은 찾을 수 없었지만, 비슷한 효과를 보여주는 영상이 있습니다.</h4>
<iframe src='http://serviceapi.rmcnmv.naver.com/flash/outKeyPlayer.nhn?vid=7C2D106783B1E41DCF772966AF9A0C56F1C4&outKey=V1212a4af8d464875fca0b915120ecaa4c9cfc65f0e643e8e101eb915120ecaa4c9cf&controlBarMovable=true&jsCallable=true&isAutoPlay=true&skinName=tvcast_white' frameborder='no' scrolling='no' marginwidth='0' marginheight='0' WIDTH='850' HEIGHT='400' allowfullscreen></iframe>
<h4 style=" color: #656565;">&nbsp;앞으로 안심벨로 인해 많은 여성들이 위험한 환경으로부터 자신을 지킬 수 있는 사건들이 많아지고 사회도 좀 더 안전하게 변화할 것이라고 예상합니다.</h4>
{%endblock content%}

introduce/templates/introduce/future.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'introduce:index'%}{%endblock%}
{%block srctwo%}{% url 'introduce:story'%}{%endblock%}
{%block srcthree%}{% url 'introduce:effect'%}{%endblock%}
{%block srcfour%}{% url 'introduce:future'%}{%endblock%}
{%block onetitle%}안심벨이란?{%endblock%}
{%block twotitle%}안심벨의 이야기{%endblock%}
{%block threetitle%}안심벨로 인해 생긴일{%endblock%}
{%block fourtitle%}안심벨의 미래{%endblock%}
{%block content%}
<style>
#logo1{
  width:450px;
  height: 250px;
}

p{
  font-size: 18px;
}

h4{
  line-height: 30px;
}
</style>
<h1 style="color: rgb(104, 164, 196);">안심벨의 미래</h1>
<h4  style=" color: #656565;" > &nbsp; 앞으로 안심벨은 많은 여성들의 안전을 지켜나가는 사건들이 많아질 것이고, 안심벨은 시스템의 발전으로 단지 공중화장실만 설치하지 않고 어두운 골목, 어두운 공원 등 안전하지 않다고 생각하는 각종 지역에도 설치될 예정이라고 합니다.</h4>
<img id="logo1" alt="" src="{% static 'img/news8.png'%}" />
<br>
<br>
<p><a href="http://www.gwmirae.kr/news/articleView.html?idxno=17038">횡성군, 공중화장실 여성 안심벨 확대 설치 - 강원미래신문</a></p>
<p><a href="http://m.blog.daum.net/6320898/1294">[안심벨] 우승희 의원 안심벨사업 통합관리,공중화장실 ... - Daum 블로그</a></p>
<p><a href="http://afef.asiae.co.kr/2017/forum_news_view.htm?pg=1&idxno=2016110311401793949">우승희 전남도의원, 도내 공중화장실 안심벨 설치 1.9% 불과</a></p>
<p><a href="http://urban114.com/news/detail.php?wr_id=3462">도시미래신문:국립공원 공중화장실 143곳, '여성 안심벨' 설치</a></p>
<br>
<h4  style=" color: #656565;" > &nbsp; 또한, 안심벨뿐만 아니라 앱으로 하는 기능, 좀 더 보편적으로 널리 어떠한 공간에서도 자신을 지킬 수 있도록 하는 각종 시스템들이 생겨 사회가 좀 더 안전하게 되고 여성들뿐만 아니라 남성들과 어린이와 노약자들도 편리하게 생활하고 안전을 지킬 수 있는 사회를 만들어갈 것이라 생각합니다.</h4>
{%endblock content%}

introduce/templates/introduce/index.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'introduce:index'%}{%endblock%}
{%block srctwo%}{% url 'introduce:story'%}{%endblock%}
{%block srcthree%}{% url 'introduce:effect'%}{%endblock%}
{%block srcfour%}{% url 'introduce:future'%}{%endblock%}

{%block onetitle%}안심벨이란?{%endblock%}
{%block twotitle%}안심벨의 이야기{%endblock%}
{%block threetitle%}안심벨로 인해 생긴일{%endblock%}
{%block fourtitle%}안심벨의 미래{%endblock%}
{%block content%}
<style>
h4{
  line-height: 30px;
}
</style>
<h1 style="color: rgb(104, 164, 196);">안심벨이란?</h1>
<h4    style=" color: #656565;" > &nbsp;요즘 사건 사고가 많이 나서 그런지 공중 화장실 뿐만 아니라 공원, 지하 주차장 등 인적이 드문 장소에 안심벨을 설치하려는 곳이 많아지고 있습니다.</h4>
<h4  style=" color: #656565;" > &nbsp;안심벨은 주로 화장실 비상벨로 많이 설치가 되고 있으며 학교폭력 방지용, 지하주차장, 공중화장실, 공원 화장실 비상벨 등 다양하게 설치되고 있습니다. 인적이 드물고 위험상황이 발생할 수 있는 모든 곳에 설치가 가능해 오늘날 여성들의 안전을 책임지고 있습니다.</h4>
<h4 style=" color: #656565;" > &nbsp;최근에는 경찰서와 연동하는 안심벨 시스템을 많이 선호해 그러한 시스템 형태로써 많이 나오고 있습니다.
이러한 안심벨 시스템 형태를 잘 보여주는 한 예들이 있어 영상을 보며 좀 더 쉽게 이해해봅시다.</h4>
<iframe width="850" height="400" src="https://www.youtube.com/embed/SIbrUqg0lWs" frameborder="0" allowfullscreen></iframe>
<h4 style=" color: #656565;" >&nbsp;영상에서 본 듯이 안심벨은 위급한 상황에서 안심벨을 누르면 근처 경찰서에 신고가 가 빠르게 대처할 수 있도록 작동하고 있습니다.</h4>
<iframe width="850" height="400" src="https://www.youtube.com/embed/q8FO3XSLZWo" frameborder="0" allowfullscreen></iframe>
<h4 style=" color: #656565;" >&nbsp;현재 이러한 안심벨은 시흥시뿐만 아니라 여러 지역에서 공중화장실과 같은 곳에 널리 보편화 되어가고 있어 여성들의 불안감을 조금씩 덜어주고 있습니다.</h4>
{%endblock content%}

introduce/templates/introduce/story.html
{% extends "base.html" %}

{% load staticfiles %}

{%block srcone%}{% url 'introduce:index'%}{%endblock%}
{%block srctwo%}{% url 'introduce:story'%}{%endblock%}
{%block srcthree%}{% url 'introduce:effect'%}{%endblock%}
{%block srcfour%}{% url 'introduce:future'%}{%endblock%}

{%block onetitle%}안심벨이란?{%endblock%}
{%block twotitle%}안심벨의 이야기{%endblock%}
{%block threetitle%}안심벨로 인해 생긴일{%endblock%}
{%block fourtitle%}안심벨의 미래{%endblock%}
{%block content%}
<style>
#logo{
  width:55px;
  height: 50px;
}
#logo1{
  width:300px;
  height: 250px;
}
h4{
  line-height: 30px;
}
</style>
<h1 style="color: rgb(104, 164, 196);"><img id="logo" alt="" src="{% static 'img/bell.png'%}" />&nbsp;안심벨의 이야기
<img id="logo" alt="" src="{% static 'img/bell.png'%}" /></h4>
<h4  style=" color: #656565;">&nbsp;안녕? 나는 안심벨이야!</h4>
<h4  style=" color: #656565;">&nbsp;나는 사회적 약자인 여성의 안전을 지켜주기 위해 만들어 졌어.</h4>
<h4  style=" color: #656565;">&nbsp;오늘날 많은 사건 사고로 현재 많은 여성들이 많은 불안감에 떨고 있다고 해.</h4>
<img id="logo1" alt="" src="{% static 'img/news3.png'%}" />
<h4  style=" color: #656565;">&nbsp;하지만 이러한 불안들은 증가하는데 그에 따른 예방책은 아직도 미미하게 변화해 아직도 여성들의 안전이 많이 위협당하고 있고... </h4>
<h4><img id="logo1" alt="" src="{% static 'img/news4.png'%}" /><img id="logo1" alt="" src="{% static 'img/news7.png'%}" /></h4>
<h4  style=" color: #656565;">&nbsp;내가 지금까지 봐왔던 관점에서 예방에 가장 무감각한 지역이 제주도였었어. 하지만 제주도에서도 얼마 전 이러한 범죄 예방책에 대한 각성을 하게 된 사건이 있었는데, 그 사건은 제주 시청에서 일어난 “강간미수사건”이였지.</h4>
<img id="logo1" alt="" src="{% static 'img/news1.png'%}" /><img id="logo1" alt="" src="{% static 'img/news2.png'%}" />
<h4  style=" color: #656565;">&nbsp;이러한 사건으로 제주 도청에서는 안심벨 설치에 중요성을 알게 되었고, 안심벨의 설치를 시작하게 되었어~!</h4>
<h4  style=" color: #656565;">&nbsp;아직도 안심벨이 보편적으로 전부 각 칸마다 설치는 되어있지 않고 모든 공중화장실에 설치되어있지 않지만 앞으로 안심벨 설치 동향은 점 점 더 보편적일 것이라고 생각해!</h4>
<img id="logo1" alt="" src="{% static 'img/news5.png'%}" /><img id="logo1" alt="" src="{% static 'img/news6.png'%}" />
<h4  style=" color: #656565;">&nbsp;앞으로 나를 더 찾아주고 이곳, 저곳에 설치가 되어 여성들이 조금 더 안심할 수 있는 사회를 만드는 게 내 꿈이야.</h4>
{%endblock content%}

jejudaum/templates/jejudaum/index.html
{% extends "com.html" %}

{% load staticfiles %}


{%block content%}

<h1>제주대학교 정문 후문 원룸 리스트입니다.</h1>
<a href="{% url 'jejudaum:room_list'%}">
  리스트 보기
</a>

{%endblock content%}